# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[30,)" #mandatory (28 is current forge version)
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/Ephys/minecraft-magic-feather/issues"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="magicfeather" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${file.jarVersion}" #mandatory
 # A display name for the mod
displayName="Magic Feather" #mandatory
# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="http://myurl.me/" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://www.curseforge.com/minecraft/mc-mods/magic-feather"
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="logo.png"
# A text field displayed in the mod UI
credits="RWTema for the original angel ring"
# A text field displayed in the mod UI
authors="Ephys, EizhFox"
# The description text for the mod (multi line!) (#mandatory)
description='''
Magic Feather is an alternative take on the Angel Ring item from Extra Utilities.

It balances creative flight by making it only available around Beacons, thus forcing the player
to use alternative methods of travel when exploring.
'''
[[dependencies.magicfeather]]
    modId="forge"
    mandatory=true
    versionRange="[30,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.magicfeather]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.magicfeather]]
    modId="cookiecore"
    mandatory=true
    versionRange="[1.15.1-2.1.0,)"
    ordering="AFTER"
    side="BOTH"
